import {
  ArrayOfRule,
  ArrayRule,
  BooleanRule,
  ConfirmedRule,
  EmailRule,
  FloatRule,
  InRule,
  IntRule,
  LengthRule,
  LocalizedRule,
  MaxLengthRule,
  MaxRule,
  MinLengthRule,
  MinRule,
  NumberRule,
  ObjectRule,
  RequiredIfRule,
  RequiredRule,
  StringRule,
  UniqueRule,
  UrlRule,
  ValidationConfigurations,
} from "@mongez/warlock";

const validationConfigurations: ValidationConfigurations = {
  stopOnFirstFailure: true,
  returnErrorStrategy: "first",
  responseStatus: 400,
  rules: {
    unique: UniqueRule,
    requiredIf: RequiredIfRule,
    required: RequiredRule,
    localized: LocalizedRule,
    string: StringRule,
    object: ObjectRule,
    confirmed: ConfirmedRule,
    in: InRule,
    min: MinRule,
    max: MaxRule,
    minLength: MinLengthRule,
    length: LengthRule,
    maxLength: MaxLengthRule,
    email: EmailRule,
    int: IntRule,
    float: FloatRule,
    number: NumberRule,
    arrayOf: ArrayOfRule,
    array: ArrayRule,
    boolean: BooleanRule,
    url: UrlRule,
  },
  keys: {
    response: "messages",
    inputKey: "key",
    inputError: "error",
    inputErrors: "errors",
  },
};

export default validationConfigurations;
